{% set name = "py-find-1st" %}
{% set version = "1.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py_find_1st-{{ version }}.tar.gz
  sha256: 8a7bcbc6a4144a58cfc0e5f4e2affd983e686cef54b0e81e29c0be15248f5e1f

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.13.0
  run:
    - numpy >=1.13.0
    - python
    - setuptools

test:
  imports:
    - utils_find_1st
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roebel/py_find_1st
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: 'Numpy extension for finding the first element in an 1D array fullfilling a given condition'
  description: |
    py_find_1st is a numpy extension that allows to find the first index
    into an 1D-array that validates a boolean condition that can consist
    of a comparison operator and a limit value.
  doc_url: https://github.com/roebel/py_find_1st
  dev_url: https://github.com/roebel/py_find_1st

extra:
  recipe-maintainers:
    - jan-janssen
